import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

final List<String> _prioList = [
  // --- KØBENHAVN & OMREGN (S-tog, Metro & Regional) ---
  "København H",
  "Nørreport St.",
  "Vesterport St.",
  "Østerport St.",
  "Nordhavn St.",
  "Svanemøllen St.",
  "Hellerup St.",
  "Bernstorffsvej St.",
  "Gentofte St.",
  "Vangede St.",
  "Dyssegård St.",
  "Emdrup St.",
  "Ryparken St.",
  "Bispebjerg St.",
  "Nørrebro St.",
  "Fuglebakken St.",
  "Grøndal St.",
  "Flintholm St.",
  "C.F. Richs Vej St.",
  "KB Hallen St.",
  "Ålholm St.",
  "Danshøj St.",
  "Vigerslev Allé St.",
  "København Syd St.",
  "Sydhavn St.",
  "Dybbølsbro St.",
  "Valby St.",
  "Hvidovre St.",
  "Rødovre St.",
  "Brøndbyøster St.",
  "Glostrup St.",
  "Albertslund St.",
  "Taastrup St.",
  "Høje Taastrup St.",
  "Vanløse St.",
  "Jyllingevej St.",
  "Islev St.",
  "Danshøj St.",
  "Herlev St.",
  "Skovlunde St.",
  "Malmparken St.",
  "Ballerup St.",
  "Måløv St.",
  "Kildedal St.",
  "Veksø St.",
  "Stenløse St.",
  "Egedal St.",
  "Ølstykke St.",
  "Frederikssund St.",
  "Åmarken St.",
  "Friheden St.",
  "Avedøre St.",
  "Brøndby Strand St.",
  "Vallensbæk St.",
  "Ishøj St.",
  "Hundige St.",
  "Greve St.",
  "Karlslunde St.",
  "Solrød Strand St.",
  "Jersie St.",
  "Køge Nord St.",
  "Ølby St.",
  "Køge St.",
  "Kildeskov St.",
  "Charlottenlund St.",
  "Ordrup St.",
  "Klampenborg St.",
  "Jægersborg St.",
  "Lyngby St.",
  "Sorgenfri St.",
  "Virum St.",
  "Holte St.",
  "Birkerød St.",
  "Allerød St.",
  "Hillerød St.",
  "Kildebakke St.",
  "Buddinge St.",
  "Stengården St.",
  "Bagsværd St.",
  "Skovbrynet St.",
  "Hareskov St.",
  "Værløse St.",
  "Farum St.",

  // --- SJÆLLAND, LOLLAND & FALSTER (Regional & Lokaltog) ---
  "Hedehusene St.",
  "Roskilde St.",
  "Viby Sjælland St.",
  "Borup St.",
  "Ringsted St.",
  "Sorø St.",
  "Slagelse St.",
  "Korsør St.",
  "Lejre St.",
  "Hvalsø St.",
  "Tølløse St.",
  "Vipperød St.",
  "Holbæk St.",
  "Regstrup St.",
  "Knabstrup St.",
  "Mørkøv St.",
  "Jyderup St.",
  "Svebølle St.",
  "Kalundborg Øst St.",
  "Kalundborg St.",
  "Gadstrup St.",
  "Havdrup St.",
  "Lille Skensved St.",
  "Ølby St.",
  "Herfølge St.",
  "Tureby St.",
  "Haslev St.",
  "Holme-Olstrup St.",
  "Næstved Nord St.",
  "Næstved St.",
  "Lundby St.",
  "Vordingborg St.",
  "Nørre Alslev St.",
  "Eskilstrup St.",
  "Nykøbing F. St.",
  "Øster Toreby St.",
  "Grænge St.",
  "Sakskøbing St.",
  "Maribo St.",
  "Ryde St.",
  "Søllested St.",
  "Avnede St.",
  "Nakskov St.",
  "Gørlev St.",
  "Høng St.",
  "Ruds Vedby St.",
  "Stenlille St.",
  "Dianalund St.",
  "Ny Hagested St.",
  "Gislinge St.",
  "Sandby St.",
  "Svinninge St.",
  "Hørve St.",
  "Fårevejle St.",
  "Asnæs St.",
  "Grevinge St.",
  "Nr. Asmindrup St.",
  "Nykøbing Sj. St.",
  "Snekkersten St.",
  "Espergærde St.",
  "Humlebæk St.",
  "Nivå St.",
  "Kokkedal St.",
  "Rungsted Kyst St.",
  "Vedbæk St.",
  "Skodsborg St.",
  "Grønnehave St.",
  "Marienlyst St.",
  "Hellebæk St.",
  "Ålsgårde St.",
  "Skibstrup St.",
  "Saunte St.",
  "Karinebæk St.",
  "Dronningmølle St.",
  "Firhøj St.",
  "Gilleleje St.",
  "Gribsø St.",
  "Kagerup St.",
  "Mårum St.",
  "Helsinge St.", "Duemose St.", "Vejby St.", "Tisvildeleje St.",

  // --- FYN ---
  "Odense St.",
  "Odense Sygehus St.",
  "Fruens Bøge St.",
  "Hjallese St.",
  "Højby St.",
  "Årslev St.",
  "Pederstrup St.",
  "Ringe St.",
  "Rudme St.",
  "Kværndrup St.",
  "Stenstrup St.",
  "Stenstrup Syd St.",
  "Svendborg Vest St.",
  "Svendborg St.",
  "Nyborg St.",
  "Langeskov St.",
  "Marslev St.",
  "Middelfart St.",
  "Kauslunde St.",
  "Nørre Åby St.",
  "Ejby St.",
  "Gelsted St.",
  "Aarup St.",
  "Bred St.",
  "Skalbjerg St.",
  "Tommerup St.",
  "Holmstrup St.",

  // --- JYLLAND (Hovedbaner & GoCollective) ---
  "Fredericia St.",
  "Taulov St.",
  "Kolding St.",
  "Lunderskov St.",
  "Vejen St.",
  "Brørup St.",
  "Holsted St.",
  "Gørding St.",
  "Bramming St.",
  "Esbjerg St.",
  "Vejle St.",
  "Hedensted St.",
  "Horsens St.",
  "Skanderborg St.",
  "Viby J St.",
  "Aarhus H",
  "Hinnerup St.",
  "Hadsten St.",
  "Langå St.",
  "Randers St.",
  "Hobro St.",
  "Arden St.",
  "Skørping St.",
  "Støvring St.",
  "Svenstrup St.",
  "Skalborg St.",
  "Aalborg St.",
  "Lindholm St.",
  "Brønderslev St.",
  "Vrå St.",
  "Hjørring St.",
  "Sindal St.",
  "Tolne St.",
  "Kvissel St.",
  "Frederikshavn St.",
  "Vojens St.",
  "Rødekro St.",
  "Tinglev St.",
  "Padborg St.",
  "Gråsten St.",
  "Sønderborg St.",
  "Varde St.",
  "Varde Kaserne St.",
  "Varde Nord St.",
  "Guldager St.",
  "Sig St.",
  "Tistrup St.",
  "Ølgod St.",
  "Lyne St.",
  "Tarm St.",
  "Skjern St.",
  "Lem St.",
  "Ringkøbing St.",
  "Heel St.",
  "Tim St.",
  "Ulfborg St.",
  "Vemb St.",
  "Bækmarksbro St.",
  "Lemvig St.",
  "Harboøre St.",
  "Thyborøn St.",
  "Struer St.",
  "Hvidbjerg St.",
  "Oddesund Nord St.",
  "Hurup Thy St.",
  "Bedsted Thy St.",
  "Snedsted St.",
  "Thisted St.",
  "Holstebro St.",
  "Aulum St.",
  "Vildbjerg St.",
  "Herning St.",
  "Herning Messecenter St.",
  "Ikast St.",
  "Bording St.",
  "Engesvang St.",
  "Silkeborg St.",
  "Svejbæk St.",
  "Laven St.",
  "Ry St.",
  "Alken St.",
  "Skive St.",
  "Vinderup St.",
  "Viborg St.",
  "Rødkærsbro St.",
  "Bjerringbro St.",
  "Ulstrup St.",
  "Give St.",
  "Thyregod St.",
  "Brande St.",
  "Gødstrup St.", "Troldhede St.", "Kibæk St.", "Studsgård St.",

  // --- NORDJYSKE JERNBANER ---
  "Hirtshals St.",
  "Emmersbæk St.",
  "Horne St.",
  "Tornby St.",
  "Vidstrup St.",
  "Vellingshøj St.",
  "Hjørring Øst St.",
  "Skagen St.",
  "Frederikshavn St.",
  "Jerup St.",
  "Bunken St.",
  "Hulsig St.",
  "Napstjært St.",
  "Rimmen St.",
  "Strandby St.",

  // --- LETBANE (Aarhus & Odense) ---
  "Dokk1 St.",
  "Skolebakken St.",
  "Østbanetorvet St.",
  "Risskov Strandpark St.",
  "Vestre Strandallé St.",
  "Torsøvej St.",
  "Lystrup St.",
  "Hovmarken St.",
  "Hornslet St.",
  "Mørke St.",
  "Ryomgård St.",
  "Kolind St.",
  "Trustrup St.",
  "Grenaa St.",
  "Aarhus Universitetshospital St.",
  "Skejby St.",
  "Gl. Skejby St.",
  "Humlehuse St.",
  "Lisbjerg St.",
  "Lisbjergskolen St.",
  "Nye St.",
  "Viby J (Letbane)",
  "Gunnar Clausens Vej St.",
  "Tranbjerg St.",
  "Mårslet St.",
  "Beder St.",
  "Mallling St.",
  "Odder St.",
  "Tarup Center St.",
  "Højstrup St.",
  "Bolbro St.",
  "Vestre Stationsvej St.",
  "Kongensgade St.",
  "Albani Torv St.",
  "Bennediks Plads St.",
  "Palnatokesvej St.",
  "Østerbæksvej St.",
  "Cortex Park St.",
  "SDU St.",
  "Hospital Syd St.",

  // --- METRO (Komplet M1-M4) ---
  "Vanløse St.",
  "Flintholm St.",
  "Lindevang St.",
  "Fasanvej St.",
  "Frederiksberg St.",
  "Forum St.",
  "Peblinge Sø St.",
  "Rådhuspladsen St.",
  "Gammel Strand St.",
  "Kongens Nytorv St.",
  "Marmorkirken St.",
  "Østerport St.",
  "Trianglen St.",
  "Poul Henningsens Plads St.",
  "Vibenshus Runddel St.",
  "Skjolds Plads St.",
  "Nørrebro St.",
  "Nuuks Plads St.",
  "Aksel Møllers Have St.",
  "Frederiksberg Allé St.",
  "Enghave Plads St.",
  "København H (Metro)",
  "Havneholmen St.",
  "Enghave Brygge St.",
  "Sluseholmen St.",
  "Mozarts Plads St.",
  "København Syd St. (Metro)",
  "Orientkaj St.",
  "Nordhavn St. (Metro)",
];

Future<void> main() async {
  Map<String, dynamic> stationMap = {};
  print("Henter koordinater for ${_prioList.length} stationer...");

  for (var station in _prioList) {
    final uri = Uri.parse(
      'https://www.rejseplanen.dk/bin/rest.exe/location.name?input=${Uri.encodeComponent(station)}&format=json',
    );

    try {
      final response = await http.get(uri);

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        final locations = data['LocationList']['StopLocation'];

        // Håndtering af hvis Rejseplanen returnerer en liste eller et enkelt objekt
        var bestMatch;
        if (locations is List) {
          bestMatch = locations.first;
        } else {
          bestMatch = locations;
        }

        if (bestMatch != null) {
          double lat = double.parse(bestMatch['y']) / 1000000;
          double lng = double.parse(bestMatch['x']) / 1000000;

          stationMap[station] = {"lat": lat, "lng": lng};
          print("✅ Fundet: $station ($lat, $lng)");
        }
      }
    } catch (e) {
      print("❌ Fejl ved $station: $e");
    }

    await Future.delayed(Duration(milliseconds: 200));
  }

  final resultFile = File('station_data.txt');
  await resultFile.writeAsString(json.encode(stationMap));

  print("\n--- FÆRDIG! ---");
  print("Alle koordinater er gemt i filen 'station_data.txt'");
}
