name: samkorsel_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # Her er de pakker vi skal bruge:
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  # DE NYE PAKKER:
  http: ^1.6.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  flutter_stripe: ^10.1.0 
  url_launcher: ^6.2.0 
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Her tilføjer vi din JSON fil
  assets:
    - assets/station_taxa.json
    - assets/map_pattern.png